name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
      shell: pwsh

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: pwsh

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile main.py --name Wechat-Emotion-Parser
      shell: pwsh

    - name: Archive build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Wechat-Emotion-Parser
        path: dist/Wechat-Emotion-Parser.exe
